### ISSUE TITLE
Unable to save page updates on a site running CB2

### ISSUE THREAD

**Issue by Dchyk** [Dental-Revenue/Codebase-2-Dev#11]
Nothing happens when users attempt to save updates to any page on this site, and adding modules to a new page seems buggy as well (nothing happens when "add new module" is clicked). 

This is the site in question: https://fuller2019.wpengine.com/

If you would like to poke around, use these WP credentials:

UN: fuller2019
PW: NKz8N@rWibGinOpS

Error log from WPEngine:

[Mon Mar 18 12:59:13.017319 2019] [php7:notice] [pid 10625] [client 144.121.139.10:48303] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY display_order ASC /* From [fuller2019.wpengine.com/wp-admin/admin.php?p' at line 1 for query SELECT * FROM modules WHERE page = ORDER BY display_order ASC /* From [fuller2019.wpengine.com/wp-admin/admin.php?page=manage-modules&editing=] in [/nas/content/live/fuller2019/wp-content/themes/codebase-2/inc/custom-modules.php:115] */ made by do_action('admin_page_manage-modules'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, render_modules, referer: https://fuller2019.wpengine.com/wp-admin/post-new.php?post_type=page

This has not been observed on any other sites we've installed CB2 on so far, only this one.
--

**Comment by ryanatduckpin** [comment]
Buggy Add Module Experience:
When you enter into the module editor, you will see appended to the end of the url a http post attribute: editing=<post_ID>. When a post is first created, it does not get assigned a post id until it is published or saved to a draft. My latest commit fixes this issue.

Page Not Updating:
There are several required fields in the modules that have been selected on the homepage that was preventing the page updating. We have required because it without these items, the module will not function properly. If you would like us to take away required fields for initial build purposes, let us know. If you would like a list of all required fields to look out for, I can provide that as well.

**Comment by Dchyk** [comment]
Thanks, Ryan - to your second note, I understand what you're saying. Can you please provide us with a comprehensive set of developer notes including Admin UI things like required fields, and anything else that may be of note about CB2 so that we don't have to bother you for small questions? For example, a rundown of the theme's architecture, like how style.php is processing the sass partials, would be really helpful for us to have for reference going forward. Thank you!
